def dicionario():
    dicionario_final = {
    "PROGRAM": {
        "ident": ["STATEMENT"],
        "return": ["STATEMENT"],
        ";": ["STATEMENT"],
        "for": ["STATEMENT"],
        "{": ["STATEMENT"],
        "if": ["STATEMENT"],
        "int": ["STATEMENT"],
        "break": ["STATEMENT"],
        "float": ["STATEMENT"],
        "print": ["STATEMENT"],
        "string": ["STATEMENT"],
        "read": ["STATEMENT"],
        "def": ["FUNCLIST"],
        "$": ["&"],
    },
    "FUNCLIST": {
        "def": ["FUNCDEF", "FUNCLIST'"],
    },
    "FUNCLIST'": {
        "def": ["FUNCDEF", "FUNCLIST'"],
        "$": ["&"],
    },
    "FUNCDEF": {
        "def": ["def", "ident", "(", "PARAMLIST", ")", "{", "STATELIST", "}"],
    },
    "PARAMLIST": {
        "float": ["PARAMETRO", "PARAMLIST'"],
        "string": ["PARAMETRO", "PARAMLIST'"],
        "int": ["PARAMETRO", "PARAMLIST'"],
        ")": ["&"],
    },
    "PARAMETRO": {
        "int": ["int", "ident"],
        "float": ["float", "ident"],
        "string": ["string", "ident"],
    },
    "PARAMLIST'": {
        ",": [",", "PARAMETRO", "PARAMLIST'"],
        ")": ["&"],
    },
    "STATEMENT": {
        "float": ["VARDECL", ";"],
        "string": ["VARDECL", ";"],
        "int": ["VARDECL", ";"],
        "ident": ["ATRIBSTAT", ";"],
        "print": ["PRINTSTAT", ";"],
        "read": ["READSTAT", ";"],
        "return": ["RETURNSTAT", ";"],
        "if": ["IFSTAT"],
        "for": ["FORSTAT"],
        "{": ["{", "STATELIST", "}"],
        "break": ["break", ";"],
        ";": [";"],
    },
    "VARDECL": {
        "int": ["int", "ident", "CONSTANTE"],
        "float": ["float", "ident", "CONSTANTE"],
        "string": ["string", "ident", "CONSTANTE"],
    },
    "CONSTANTE": {
        "[": ["[", "const_inteiro", "]", "CONSTANTE"],
        ";": ["&"],
    },
    "ATRIBSTAT": {
        "ident": ["LVALUE", "=", "ATRIBSTAT'"],
    },
    "ATRIBSTAT'": {
        "ident": ["EXPRESSION"],
        "null": ["EXPRESSION"],
        "-": ["EXPRESSION"],
        "const_float": ["EXPRESSION"],
        "const_string": ["EXPRESSION"],
        "const_inteiro": ["EXPRESSION"],
        "(": ["EXPRESSION"],
        "+": ["EXPRESSION"],
        "new": ["ALLOCEXPRESSION"],
    },
    "FUNCCALL": {
        "(": ["(", "PARAMLISTCALL", ")"],
    },
    "PARAMLISTCALL": {
        "ident": ["ident", "PARAMLISTCALL'"],
        ")": ["&"],
    },
    "PARAMLISTCALL'": {
        ",": [",", "ident", "PARAMLISTCALL'"],
        ")": ["&"],
    },
    "PRINTSTAT": {
        "print": ["print", "EXPRESSION"],
    },
    "READSTAT": {
        "read": ["read", "LVALUE"],
    },
    "RETURNSTAT": {
        "return": ["return"],
    },
    "IFSTAT": {
        "if": ["if", "(", "EXPRESSION", ")", "STATEMENT", "IFSTAT'"],
    },
    "IFSTAT'": {
        "else": ["else", "STATEMENT"],
        "ident": ["&"],
        "return": ["&"],
        ";": ["&"],
        "for": ["&"],
        "{": ["&"],
        "if": ["&"],
        "int": ["&"],
        "break": ["&"],
        "float": ["&"],
        "print": ["&"],
        "string": ["&"],
        "read": ["&"],
        "}": ["&"],
        "$": ["&"],
    },
    "FORSTAT": {
        "for": ["for", "(", "ATRIBSTAT", ";", "EXPRESSION", ";", "ATRIBSTAT", ")", "STATEMENT"],
    },
    "STATELIST": {
        "ident": ["STATEMENT", "STATELIST"],
        "return": ["STATEMENT", "STATELIST"],
        ";": ["STATEMENT", "STATELIST"],
        "for": ["STATEMENT", "STATELIST"],
        "{": ["STATEMENT", "STATELIST"],
        "if": ["STATEMENT", "STATELIST"],
        "int": ["STATEMENT", "STATELIST"],
        "break": ["STATEMENT", "STATELIST"],
        "float": ["STATEMENT", "STATELIST"],
        "print": ["STATEMENT", "STATELIST"],
        "string": ["STATEMENT", "STATELIST"],
        "read": ["STATEMENT", "STATELIST"],
        "}": ["&"],
    },
    "ALLOCEXPRESSION": {
        "new": ["new", "TIPO", "[", "NUMEXPRESSION", "]", "ALLOCEXPRESSION'"],
    },
    "TIPO": {
        "int": ["int"],
        "float": ["float"],
        "string": ["string"],
    },
    "ALLOCEXPRESSION'": {
        "[": ["[", "NUMEXPRESSION", "]"],
        ")": ["&"],
        ";": ["&"],
    },
    "EXPRESSION": {
        "ident": ["NUMEXPRESSION", "COMPARACAO"],
        "null": ["NUMEXPRESSION", "COMPARACAO"],
        "-": ["NUMEXPRESSION", "COMPARACAO"],
        "const_float": ["NUMEXPRESSION", "COMPARACAO"],
        "const_string": ["NUMEXPRESSION", "COMPARACAO"],
        "const_inteiro": ["NUMEXPRESSION", "COMPARACAO"],
        "(": ["NUMEXPRESSION", "COMPARACAO"],
        "+": ["NUMEXPRESSION", "COMPARACAO"],
    },
    "COMPARACAO": {
        "<": ["<", "NUMEXPRESSION"],
        ">": [">", "NUMEXPRESSION"],
        "<=": ["<=", "NUMEXPRESSION"],
        ">=": [">=", "NUMEXPRESSION"],
        "==": ["==", "NUMEXPRESSION"],
        "!=": ["!=", "NUMEXPRESSION"],
        ")": ["&"],
        ";": ["&"],
    },
    "NUMEXPRESSION": {
        "ident": ["TERM", "NUMEXPRESSION'"],
        "null": ["TERM", "NUMEXPRESSION'"],
        "-": ["TERM", "NUMEXPRESSION'"],
        "const_float": ["TERM", "NUMEXPRESSION'"],
        "const_string": ["TERM", "NUMEXPRESSION'"],
        "const_inteiro": ["TERM", "NUMEXPRESSION'"],
        "(": ["TERM", "NUMEXPRESSION'"],
        "+": ["TERM", "NUMEXPRESSION'"],
    },
    "NUMEXPRESSION'": {
        "+": ["+", "TERM", "NUMEXPRESSION'"],
        "-": ["-", "TERM", "NUMEXPRESSION'"],
        ")": ["&"],
        "]": ["&"],
        ";": ["&"],
        "!=": ["&"],
        ">=": ["&"],
        "<": ["&"],
        "<=": ["&"],
        "==": ["&"],
        ">": ["&"],
    },
    "TERM": {
        "ident": ["UNARYEXPR", "TERM'"],
        "null": ["UNARYEXPR", "TERM'"],
        "-": ["UNARYEXPR", "TERM'"],
        "const_float": ["UNARYEXPR", "TERM'"],
        "const_string": ["UNARYEXPR", "TERM'"],
        "const_inteiro": ["UNARYEXPR", "TERM'"],
        "(": ["UNARYEXPR", "TERM'"],
        "+": ["UNARYEXPR", "TERM'"],
    },
    "TERM'": {
        "*": ["*", "UNARYEXPR", "TERM'"],
        "/": ["/", "UNARYEXPR", "TERM'"],
        "%": ["%", "UNARYEXPR", "TERM'"],
        ")": ["&"],
        "]": ["&"],
        ";": ["&"],
        "!=": ["&"],
        ">=": ["&"],
        "-": ["&"],
        "<": ["&"],
        "<=": ["&"],
        "==": ["&"],
        "+": ["&"],
        ">": ["&"],
    },
    "UNARYEXPR": {
        "ident": ["OPERADORES", "FACTOR"],
        "null": ["OPERADORES", "FACTOR"],
        "-": ["OPERADORES", "FACTOR"],
        "const_float": ["OPERADORES", "FACTOR"],
        "const_string": ["OPERADORES", "FACTOR"],
        "const_inteiro": ["OPERADORES", "FACTOR"],
        "(": ["OPERADORES", "FACTOR"],
        "+": ["OPERADORES", "FACTOR"],
    },
    "OPERADORES": {
        "+": ["+"],
        "-": ["-"],
        "ident": ["&"],
        "null": ["&"],
        "const_inteiro": ["&"],
        "(": ["&"],
        "const_float": ["&"],
        "const_string": ["&"],
    },
    "FACTOR": {
        "const_inteiro": ["const_inteiro"],
        "const_float": ["const_float"],
        "const_string": ["const_string"],
        "null": ["null"],
        "(": ["(", "NUMEXPRESSION", ")"],
        "ident": ["ident", "CHAMADA"],
    },
    "CHAMADA": {
        "(": ["FUNCCALL"],
        "[": ["LVALUE'"],
        ")": ["LVALUE'"],
        "]": ["LVALUE'"],
        ";": ["LVALUE'"],
        "!=": ["LVALUE'"],
        "/": ["LVALUE'"],
        ">=": ["LVALUE'"],
        "-": ["LVALUE'"],
        "<": ["LVALUE'"],
        "<=": ["LVALUE'"],
        "==": ["LVALUE'"],
        "*": ["LVALUE'"],
        "+": ["LVALUE'"],
        ">": ["LVALUE'"],
        "%": ["LVALUE'"],
    },
    "LVALUE": {
        "ident": ["ident", "LVALUE'"],
    },
    "LVALUE'": {
        "[": ["[", "NUMEXPRESSION", "]", "LVALUE'"],
        ")": ["&"],
        "]": ["&"],
        ";": ["&"],
        "!=": ["&"],
        "/": ["&"],
        ">=": ["&"],
        "-": ["&"],
        "<": ["&"],
        "<=": ["&"],
        "==": ["&"],
        "*": ["&"],
        "=": ["&"],
        "+": ["&"],
        ">": ["&"],
        "%": ["&"],
    },
}

    return dicionario_final
